import jsPDF from "jspdf";
import "jspdf-autotable";

interface VitalsPDFPatient {
  full_name: string;
  date_of_birth: string | null;
  blood_type: string | null;
  phone: string | null;
  home_address: string | null;
}

interface VitalsPDFProfile {
  chronic_conditions: string[];
  known_allergies: string | null;
  weight_kg: number | null;
  height_cm: number | null;
}

interface VitalValue {
  value: number | null;
  recorded_at: string | null;
  status?: string;
}

interface LatestVitals {
  bp: { systolic: number | null; diastolic: number | null; recorded_at: string | null; status: string } | null;
  glucose: VitalValue | null;
  heart_rate: VitalValue | null;
  temperature: VitalValue | null;
  spo2: VitalValue | null;
  weight: { value: number | null; recorded_at: string | null } | null;
  bmi: VitalValue | null;
}

interface VitalRecord {
  id: string;
  bp_systolic: number | null;
  bp_diastolic: number | null;
  blood_glucose_mg_dl: number | string | null;
  heart_rate_bpm: number | null;
  temperature_celsius: number | string | null;
  spo2_percent: number | string | null;
  weight_kg: number | string | null;
  bmi: number | string | null;
  vital_source: string;
  is_flagged: boolean;
  flagged_reasons: string[];
  recorded_at: string;
  recorded_by_user?: { full_name: string; role: string };
}

export interface VitalsPDFData {
  patient: VitalsPDFPatient;
  patientProfile: VitalsPDFProfile | null;
  vitalsHistory: VitalRecord[];
  latestVitals: LatestVitals;
  generatedAt: string;
  generatedBy: string;
}

function formatDate(d: string | null): string {
  if (!d) return "—";
  const date = new Date(d);
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function formatTime(d: string): string {
  const date = new Date(d);
  return date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true });
}

function getStatusColor(status: string): [number, number, number] {
  if (status === "critical") return [248, 113, 113];
  if (status === "warning") return [251, 191, 36];
  return [16, 185, 129];
}

export async function generateVitalsReport(data: VitalsPDFData): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  const primaryColor: [number, number, number] = [10, 126, 164];
  const darkText: [number, number, number] = [13, 27, 62];
  let currentPage = 1;
  const totalPages = { value: 1 };

  // Load logo
  let logoBase64 = "";
  try {
    const response = await fetch("/logo/fcn-logo-full.png");
    const blob = await response.blob();
    logoBase64 = await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch {
    // Logo not available, skip
  }

  // Footer
  const addFooter = () => {
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setDrawColor(...primaryColor);
      doc.setLineWidth(0.3);
      doc.line(margin, 285, pageWidth - margin, 285);
      doc.setFontSize(7);
      doc.setTextColor(100, 116, 139);
      doc.text("Foundation Care Network — Confidential Medical Record", margin, 290);
      doc.text(`Page ${i} of ${pages}`, pageWidth / 2, 290, { align: "center" });
      doc.text("Generated by FCN Digital Health System", pageWidth - margin, 290, { align: "right" });
    }
  };

  // ===== PAGE 1: HEADER =====
  if (logoBase64) {
    doc.addImage(logoBase64, "PNG", margin, 15, 45, 20);
  }
  doc.setFontSize(14);
  doc.setTextColor(...primaryColor);
  doc.text("Foundation Care Network", margin + 50, 22);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Compassion. Connection. Care.", margin + 50, 28);

  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(margin, 38, pageWidth - margin, 38);

  // Document Title
  doc.setFontSize(16);
  doc.setTextColor(...darkText);
  doc.text("PATIENT HEALTH REPORT", pageWidth / 2, 50, { align: "center" });
  doc.setDrawColor(45, 212, 191);
  doc.setLineWidth(0.8);
  doc.line(pageWidth / 2 - 40, 53, pageWidth / 2 + 40, 53);

  // Patient Info Grid
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const leftX = margin;
  const rightX = pageWidth / 2 + 5;
  let y = 65;

  doc.setFont("helvetica", "bold");
  doc.text(`Patient Name:`, leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.patient.full_name, leftX + 35, y);
  doc.setFont("helvetica", "bold");
  doc.text(`Report Period:`, rightX, y);
  doc.setFont("helvetica", "normal");
  const vitalsLen = data.vitalsHistory.length;
  const periodStart = vitalsLen > 0 ? formatDate(data.vitalsHistory[vitalsLen - 1].recorded_at) : "—";
  const periodEnd = vitalsLen > 0 ? formatDate(data.vitalsHistory[0].recorded_at) : "—";
  doc.text(`${periodStart} to ${periodEnd}`, rightX + 35, y);

  y += 7;
  doc.setFont("helvetica", "bold");
  doc.text(`Date of Birth:`, leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(formatDate(data.patient.date_of_birth), leftX + 35, y);
  doc.setFont("helvetica", "bold");
  doc.text(`Generated:`, rightX, y);
  doc.setFont("helvetica", "normal");
  doc.text(`${formatDate(data.generatedAt)} ${formatTime(data.generatedAt)}`, rightX + 35, y);

  y += 7;
  doc.setFont("helvetica", "bold");
  doc.text(`Blood Type:`, leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.patient.blood_type ?? "—", leftX + 35, y);
  doc.setFont("helvetica", "bold");
  doc.text(`Generated by:`, rightX, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.generatedBy, rightX + 35, y);

  y += 7;
  doc.setFont("helvetica", "bold");
  doc.text(`Phone:`, leftX, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.patient.phone ?? "—", leftX + 35, y);

  // Critical Flags Section
  const flaggedRecords = data.vitalsHistory.filter((v) => v.is_flagged);
  if (flaggedRecords.length > 0) {
    y += 12;
    doc.setDrawColor(248, 113, 113);
    doc.setFillColor(254, 242, 242);
    doc.roundedRect(margin, y, contentWidth, 16, 2, 2, "FD");
    doc.setFontSize(9);
    doc.setTextColor(185, 28, 28);
    doc.text(`⚠ ATTENTION: Critical readings detected in this report`, margin + 4, y + 7);
    doc.setFontSize(7);
    flaggedRecords.slice(0, 3).forEach((v, i) => {
      const reasons = (v.flagged_reasons ?? []).join(", ");
      doc.text(`${formatDate(v.recorded_at)} — ${reasons}`, margin + 8, y + 13 + i * 4);
    });
    y += 20;
  }

  // ===== VITALS SUMMARY SECTION =====
  y += 8;
  doc.setFillColor(...primaryColor);
  doc.roundedRect(margin, y, contentWidth, 7, 1, 1, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("CURRENT VITAL SIGNS SUMMARY", margin + 4, y + 5);
  y += 12;

  const vitals = data.latestVitals;
  const summaryData: { label: string; value: string; unit: string; status: string; color: [number, number, number] }[] = [
    {
      label: "Blood Pressure",
      value: vitals.bp ? `${vitals.bp.systolic}/${vitals.bp.diastolic}` : "—",
      unit: "mmHg",
      status: vitals.bp?.status ?? "normal",
      color: getStatusColor(vitals.bp?.status ?? "normal")
    },
    {
      label: "Blood Glucose",
      value: vitals.glucose ? `${vitals.glucose.value}` : "—",
      unit: "mg/dL",
      status: vitals.glucose?.status ?? "normal",
      color: getStatusColor(vitals.glucose?.status ?? "normal")
    },
    {
      label: "Heart Rate",
      value: vitals.heart_rate ? `${vitals.heart_rate.value}` : "—",
      unit: "bpm",
      status: vitals.heart_rate?.status ?? "normal",
      color: getStatusColor(vitals.heart_rate?.status ?? "normal")
    },
    {
      label: "Temperature",
      value: vitals.temperature ? `${vitals.temperature.value}` : "—",
      unit: "°C",
      status: vitals.temperature?.status ?? "normal",
      color: getStatusColor(vitals.temperature?.status ?? "normal")
    },
    {
      label: "SpO2",
      value: vitals.spo2 ? `${vitals.spo2.value}` : "—",
      unit: "%",
      status: vitals.spo2?.status ?? "normal",
      color: getStatusColor(vitals.spo2?.status ?? "normal")
    },
    {
      label: "BMI",
      value: vitals.bmi ? `${vitals.bmi.value}` : "—",
      unit: "kg/m²",
      status: vitals.bmi?.status ?? "normal",
      color: getStatusColor(vitals.bmi?.status ?? "normal")
    }
  ];

  const boxW = (contentWidth - 12) / 3;
  const boxH = 22;
  let col = 0;
  let rowY = y;
  for (const item of summaryData) {
    const bx = margin + col * (boxW + 6);
    doc.setDrawColor(...item.color);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(bx, rowY, boxW, boxH, 2, 2, "FD");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(item.label, bx + 3, rowY + 5);
    doc.setFontSize(12);
    doc.setTextColor(...darkText);
    doc.setFont("helvetica", "bold");
    doc.text(item.value, bx + 3, rowY + 15);
    doc.setFontSize(6);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    doc.text(item.unit, bx + 3 + doc.getTextWidth(item.value) + 4, rowY + 15);
    doc.setFontSize(6);
    doc.setTextColor(...item.color);
    doc.text(item.status.toUpperCase(), bx + boxW - 3, rowY + 15, { align: "right" });
    col++;
    if (col === 3) { col = 0; rowY += boxH + 4; }
  }

  y = rowY + 10;

  // ===== MEDICAL PROFILE =====
  doc.addPage();
  currentPage++;
  totalPages.value = currentPage;

  y = margin;
  doc.setFillColor(...primaryColor);
  doc.roundedRect(margin, y, contentWidth, 7, 1, 1, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("MEDICAL PROFILE", margin + 4, y + 5);
  y += 14;

  const profile = data.patientProfile;
  const chronic = profile?.chronic_conditions ?? [];
  const allergies = profile?.known_allergies ?? null;

  doc.setFontSize(9);
  doc.setTextColor(...darkText);
  doc.setFont("helvetica", "bold");
  doc.text("Chronic Conditions", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  if (chronic.length === 0) {
    doc.text("None reported", margin + 3, y + 5);
  } else {
    chronic.forEach((c, i) => {
      doc.text(`• ${c}`, margin + 3, y + 5 + i * 5);
    });
  }

  doc.setFont("helvetica", "bold");
  doc.setTextColor(...darkText);
  const allergiesX = pageWidth / 2 + 5;
  doc.text("Known Allergies", allergiesX, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(220, 38, 38);
  if (!allergies) {
    doc.text("None reported", allergiesX + 3, y + 5);
    doc.setTextColor(71, 85, 105);
  } else {
    const lines = doc.splitTextToSize(allergies, boxW);
    lines.forEach((line: string, i: number) => {
      doc.text(`⚠ ${line}`, allergiesX + 3, y + 5 + i * 5);
    });
  }

  const profileRightY = y + Math.max(5 + (chronic.length || 1) * 5, 5 + ((allergies ? doc.splitTextToSize(allergies, boxW).length : 1) * 5));
  y = profileRightY + 8;

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.text(`Height: ${profile?.height_cm ?? "—"} cm  |  Weight: ${profile?.weight_kg ?? "—"} kg  |  BMI: ${data.latestVitals.bmi?.value ?? "—"}`, margin, y);

  y += 16;

  // ===== VITALS HISTORY TABLE =====
  doc.setFillColor(...primaryColor);
  doc.roundedRect(margin, y, contentWidth, 7, 1, 1, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("VITAL SIGNS HISTORY", margin + 4, y + 5);
  y += 10;

  const tableData = data.vitalsHistory.map((v) => [
    v.is_flagged ? "⚠" : "",
    formatDate(v.recorded_at),
    formatTime(v.recorded_at),
    v.bp_systolic ? `${v.bp_systolic}/${v.bp_diastolic ?? "—"}` : "—",
    v.blood_glucose_mg_dl ? `${v.blood_glucose_mg_dl}` : "—",
    v.heart_rate_bpm ? `${v.heart_rate_bpm}` : "—",
    v.temperature_celsius ? `${v.temperature_celsius}` : "—",
    v.spo2_percent ? `${v.spo2_percent}` : "—",
    v.weight_kg ? `${v.weight_kg}` : "—",
    v.bmi ? `${v.bmi}` : "—",
    v.vital_source === "self" ? "Self" : v.vital_source === "nurse" ? "Nurse" : "Doctor"
  ]);

  (doc as any).autoTable({
    startY: y,
    head: [["", "Date", "Time", "BP", "Glucose", "HR", "Temp", "SpO2", "Weight", "BMI", "By"]],
    body: tableData,
    margin: { top: margin, bottom: margin },
    headStyles: {
      fillColor: [10, 126, 164],
      textColor: 255,
      fontSize: 7,
      fontStyle: "bold"
    },
    bodyStyles: { fontSize: 7, textColor: [71, 85, 105] },
    alternateRowStyles: { fillColor: [248, 254, 254] },
    columnStyles: {
      0: { cellWidth: 5, halign: "center" },
      1: { cellWidth: 22 },
      2: { cellWidth: 16 },
      3: { cellWidth: 16, halign: "center" },
      4: { cellWidth: 16, halign: "center" },
      5: { cellWidth: 12, halign: "center" },
      6: { cellWidth: 14, halign: "center" },
      7: { cellWidth: 12, halign: "center" },
      8: { cellWidth: 14, halign: "center" },
      9: { cellWidth: 12, halign: "center" },
      10: { cellWidth: 14, halign: "center" }
    },
    didParseCell: (data: any) => {
      if (data.column.index === 5 && data.cell.raw === "—") {
        data.cell.styles.textColor = [200, 200, 200];
      }
    }
  });

  // Disclaimer on last page
  const lastPage = doc.getNumberOfPages();
  doc.setPage(lastPage);
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  const disclaimer = "This report was generated by FCN's digital health platform. It is intended for medical reference only and should be reviewed by a licensed healthcare professional.";
  doc.text(disclaimer, margin, 275, { maxWidth: contentWidth });

  addFooter();

  const patientName = data.patient.full_name.replace(/\s+/g, "_");
  const dateStr = formatDate(data.generatedAt).replace(/\s+/g, "_");
  doc.save(`FCN_Health_Report_${patientName}_${dateStr}.pdf`);
}
